# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Per',
            fields=[
                ('PID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=20)),
                ('PNote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TB_Role',
            fields=[
                ('RoleID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=20)),
                ('RoleNote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TB_Role_Per',
            fields=[
                ('RPID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('RoleID', models.BigIntegerField()),
                ('PID', models.BigIntegerField()),
                ('Note', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TB_User',
            fields=[
                ('UID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=20)),
                ('UserPwd', models.CharField(max_length=50)),
                ('UserEmail', models.EmailField(max_length=254)),
                ('UserState', models.IntegerField(max_length=1)),
                ('UserRole', models.BigIntegerField()),
            ],
        ),
    ]
